### ISSUE TITLE
KeepInventory Plugin for Muck?

### ISSUE THREAD

**Issue by YisusClaus** [SuperGamerTron/SelfRevive#1]
Have you considered making a keepinventory plugin? Therefore, there would be no need to gather all of the dropped items when clicking "Revive".

**Comment by SuperGamerTron** [comment]
That's a good idea, I'll see if I can make that.

**Comment by SuperGamerTron** [comment]
I have just finished making it and it is now in the thunderstore.
https://muck.thunderstore.io/package/SuperGamerTron/KeepInventory/

**Comment by YisusClaus** [comment]
> I have just finished making it and it is now in the thunderstore.
> https://muck.thunderstore.io/package/SuperGamerTron/KeepInventory/
> 

Thanks, you are Awesome!
